#!/usr/bin/env python3
"""Finite checks for Finding 004 (Legendary): unit-generated residue fields in real quadratic fields.

Scope. This script checks, on actual primes, the three ELEMENTARY mechanisms of the proof
(the splitting test, the role of the unit -1 for the prime 2, and the Fibonacci twist).
It also reports how the counted primes compare with x/(log x)^2. It does NOT verify the
analytic premises taken from OpenAI manuscript family 029 (uniform zero-free strip, prime
construction, uniform explicit formula) and it is NOT a proof of the theorem, which is an
asymptotic statement. The counts below are evidence that the elementary lemmas are stated
correctly, nothing more.

Usage:  python check_unit_primitive_roots.py [--limit N] [--json]
Requires Python 3.8+ and only the standard library. Deterministic; no network access.
The script refuses to run under python -O because its checks are assertions.
"""

import argparse
import json
import math
import sys

if sys.flags.optimize:
    sys.exit("refusing to run with assertions disabled (python -O); run without -O")


def primes_up_to(n):
    """Return the list of primes <= n (sieve of Eratosthenes)."""
    sieve = bytearray([1]) * (n + 1)
    sieve[0:2] = b"\x00\x00"
    for i in range(2, int(n ** 0.5) + 1):
        if sieve[i]:
            sieve[i * i::i] = bytearray(len(range(i * i, n + 1, i)))
    return [i for i, v in enumerate(sieve) if v]


def odd_prime_factors(n, small_primes):
    """Odd prime factors of n (n <= limit^1), by trial division with the sieve list."""
    out = []
    m = n
    while m % 2 == 0:
        m //= 2
    for q in small_primes:
        if q * q > m:
            break
        if m % q == 0:
            out.append(q)
            while m % q == 0:
                m //= q
    if m > 1:
        out.append(m)
    return out


def sqrt_mod(a, p):
    """A square root of a modulo an odd prime p, or None (Tonelli-Shanks)."""
    a %= p
    if a == 0:
        return 0
    if pow(a, (p - 1) // 2, p) != 1:
        return None
    if p % 4 == 3:
        return pow(a, (p + 1) // 4, p)
    # Tonelli-Shanks for p = 1 mod 4
    q, s = p - 1, 0
    while q % 2 == 0:
        q //= 2
        s += 1
    z = 2
    while pow(z, (p - 1) // 2, p) != p - 1:
        z += 1
    m, c, t, r = s, pow(z, q, p), pow(a, q, p), pow(a, (q + 1) // 2, p)
    while t != 1:
        i, t2 = 0, t
        while t2 != 1:
            t2 = t2 * t2 % p
            i += 1
        b = pow(c, 1 << (m - i - 1), p)
        m, c, t, r = i, b * b % p, t * b * b % p, r * b % p
    return r


def generated_by_minus_one_and(eps, p, small_primes):
    """True iff {-1, eps} generate (Z/pZ)^* for the odd prime p (direct subgroup computation)."""
    # The subgroup generated by -1 and eps has order lcm(2, ord(eps)) or ord(eps);
    # compute ord(eps) by the factorization of p-1.
    n = p - 1
    order = n
    m = n
    factors = []
    while m % 2 == 0:
        m //= 2
    if n % 2 == 0:
        factors.append(2)
    factors += odd_prime_factors(n, small_primes)
    for q in factors:
        while order % q == 0 and pow(eps, order // q, p) == 1:
            order //= q
    # -1 is in <eps> iff ord(eps) is even; otherwise adjoining -1 doubles the order.
    group_order = order if order % 2 == 0 else 2 * order
    return group_order == p - 1


def lemma_test(eps, p, small_primes):
    """The proof's criterion for p = 3 (mod 4): {-1,eps} generate iff eps^((p-1)/q) != 1 for all odd q | p-1."""
    assert p % 4 == 3
    for q in odd_prime_factors(p - 1, small_primes):
        if pow(eps, (p - 1) // q, p) == 1:
            return False
    return True


def check_real_quadratic(D, unit, limit, primes, small_primes):
    """Field K = Q(sqrt D) with a fundamental unit eps = (a + b*sqrt D)/den, den in {1, 2}.

    Returns a summary dict. Primes p = 3 mod 4 that split in K are tested with both primes P above p.
    """
    a, b, den = unit
    split_count = 0
    generated_count = 0
    agreement = 0
    for p in primes:
        if p < 3 or p % 4 != 3 or D % p == 0:
            continue
        s = sqrt_mod(D, p)
        if s is None:
            continue  # inert: never unit-generated (Lemma 7(ii) direction not tested here)
        split_count += 1
        inv_den = pow(den, p - 2, p)
        e1 = (a + b * s) * inv_den % p
        e2 = (a - b * s) * inv_den % p  # the other prime above p
        g1 = generated_by_minus_one_and(e1, p, small_primes)
        g2 = generated_by_minus_one_and(e2, p, small_primes)
        # the property does not depend on the choice of P above p (Lemma 7(i): conjugate = +-eps^{-1})
        assert g1 == g2, (D, p)
        # the lemma's criterion agrees with the direct subgroup computation
        assert lemma_test(e1, p, small_primes) == g1, (D, p)
        agreement += 1
        if g1:
            generated_count += 1
    x = float(limit)
    return {
        "D": D,
        "unit": "(%d+%d*sqrt(%d))/%d" % (a, b, D, den),
        "primes_3mod4_split": split_count,
        "unit_generated": generated_count,
        "ratio_to_x_over_log2": round(generated_count / (x / math.log(x) ** 2), 3),
        "ratio_to_split_primes": round(generated_count / split_count, 4) if split_count else None,
        "criterion_agreements": agreement,
    }


def check_fibonacci(limit, primes, small_primes):
    """E2-T2 mechanism: for p = 3 mod 4 with x^2-x-1 split and {-1,phi} generating, exactly one root is a primitive root."""
    tested = 0
    one_primitive = 0
    fpr_total = 0  # primes with a Fibonacci primitive root, any residue class
    for p in primes:
        if p < 7:
            continue
        s = sqrt_mod(5, p)
        if s is None:
            continue
        inv2 = pow(2, p - 2, p)
        r1 = (1 + s) * inv2 % p
        r2 = (1 - s) * inv2 % p
        assert (r1 * r1 - r1 - 1) % p == 0 and (r2 * r2 - r2 - 1) % p == 0
        assert r1 * r2 % p == p - 1  # phi * phi' = -1
        prim = [_is_primitive(r, p, small_primes) for r in (r1, r2)]
        if any(prim):
            fpr_total += 1
        if p % 4 == 3 and generated_by_minus_one_and(r1, p, small_primes):
            tested += 1
            assert sum(prim) == 1, p  # exactly one of the two roots is a primitive root
            one_primitive += 1
    pi_x = sum(1 for p in primes if p <= limit)
    artin = 0.3739558136192022880547280543464164151116292486061
    return {
        "tested_3mod4_generated": tested,
        "exactly_one_primitive_root": one_primitive,
        "primes_with_fibonacci_primitive_root": fpr_total,
        "fraction_of_all_primes": round(fpr_total / pi_x, 5),
        "shanks_conjectured_density_27A_over_38": round(27 * artin / 38, 5),
    }


def _is_primitive(g, p, small_primes):
    n = p - 1
    fs = ([2] if n % 2 == 0 else []) + odd_prime_factors(n, small_primes)
    return all(pow(g, n // q, p) != 1 for q in fs)


def check_progression(limit, primes):
    """Lemma 6: for squarefree D, the residue class u = -1 mod f, u = 3 mod 4 consists of primes that split in K and are 3 mod 4."""
    checked = 0
    for D in range(2, 200):
        if any(D % (q * q) == 0 for q in range(2, 15)):
            continue
        f = D if D % 4 == 1 else 4 * D  # conductor of Q(sqrt D)
        M = f if f % 8 == 0 else (8 * f if f % 2 else 4 * f)  # a multiple of 8 and of f
        # u: -1 mod f and 3 mod 4 (consistent since -1 = 3 mod 4), via search
        u = next(v for v in range(1, 4 * M) if v % f == f - 1 and v % 4 == 3 and math.gcd(v, M) == 1)
        assert (u - 1) % 2 == 0 and math.gcd((u - 1) // 2, M // 2) == 1  # Prop 2.1 hypotheses with c = 2
        for p in primes:
            if p > limit or p <= 2 * D:
                continue
            if p % M == u % M:
                assert p % 4 == 3
                assert sqrt_mod(D, p) is not None, (D, p)  # splits completely in K
                checked += 1
    return {"squarefree_D_below": 200, "primes_in_progressions_checked": checked}


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--limit", type=int, default=1_000_000, help="count primes up to this bound (default 10^6)")
    ap.add_argument("--json", action="store_true", help="print only the JSON summary")
    args = ap.parse_args()
    limit = args.limit
    primes = primes_up_to(limit)
    small_primes = primes_up_to(int(limit ** 0.5) + 2)

    # (D, (a, b, den)) with fundamental unit (a + b sqrt D)/den; all five fields have class number one
    fields = [
        (2, (1, 1, 1)),    # Q(sqrt 2), eps = 1 + sqrt 2, norm -1
        (3, (2, 1, 1)),    # Q(sqrt 3), eps = 2 + sqrt 3, norm +1
        (5, (1, 1, 2)),    # Q(sqrt 5), eps = (1 + sqrt 5)/2, the golden ratio
        (13, (3, 1, 2)),   # Q(sqrt 13), eps = (3 + sqrt 13)/2, norm -1
        (14, (15, 4, 1)),  # Z[sqrt 14], Harper's field, eps = 15 + 4 sqrt 14
    ]
    results = {"limit": limit, "fields": [], "fibonacci": None, "progression": None}
    for D, unit in fields:
        results["fields"].append(check_real_quadratic(D, unit, limit, primes, small_primes))
    results["fibonacci"] = check_fibonacci(limit, primes, small_primes)
    results["progression"] = check_progression(min(limit, 200_000), primes)
    results["status"] = "passed"
    results["scope"] = "elementary lemmas and counts only; not a proof of the theorem and not a check of the analytic premises"
    if args.json:
        print(json.dumps(results))
    else:
        print(json.dumps(results, indent=2))


if __name__ == "__main__":
    main()
